apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tasks-service
  namespace: {{ .Values.namespace }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: tasks-service
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
