namespace: podpilot

mongodb:
  image: mongo:7
  port: 27017
  storage: 1Gi

usersService:
  image: eli9476/podpilot-users-service
  tag: a5dac360487e0c32d99715005f80cf226f13ef16
  port: 4001
  jwtSecret: local-dev-secret

tasksService:
  image: eli9476/podpilot-tasks-service
  tag: a5dac360487e0c32d99715005f80cf226f13ef16
  port: 4002
  jwtSecret: local-dev-secret

notificationsService:
  image: eli9476/podpilot-notifications-service
  tag: a5dac360487e0c32d99715005f80cf226f13ef16
  port: 4003

frontend:
  image: eli9476/podpilot-frontend
  tag: 2ca8a4df15b3d6471d30cd879573828bc07b3138
  port: 80
