namespace: podpilot

mongodb:
  image: mongo:7
  port: 27017
  storage: 1Gi

usersService:
  image: eli9476/podpilot-users-service
  tag: latest
  port: 4001
  jwtSecret: local-dev-secret

tasksService:
  image: eli9476/podpilot-tasks-service
  tag: latest
  port: 4002
  jwtSecret: local-dev-secret

notificationsService:
  image: eli9476/podpilot-notifications-service
  tag: latest
  port: 4003

frontend:
  image: eli9476/podpilot-frontend
  tag: latest
  port: 80
